### ISSUE TITLE
❇ Amazon Dash Buttons

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#21]
# Problem/Motivation

An add-on that would allow to easily use Amazon Dash buttons with Home Assistant.

There is currently add-on out there, but the author has signaled it might need some love.

## Ref

https://en.wikipedia.org/wiki/Amazon_Dash
https://github.com/danimtb/dasshio
https://twitter.com/Dani_MTB/status/925144577698422786

**Comment by james-fry** [comment]
There are actually two addons.
I also created one based on dasher:
https://github.com/james-fry/hassio-addons/tree/master/dasher
https://github.com/maddox/dasher

As far as I am aware dasher does not have the double trigger issue that dashio does, although config for dasher is not as simple (i.e. not integrated to hassio addon config).

**Comment by danimtb** [comment]
Actually the double trigger issue on Dasshio is solved and it is working quite well without big trouble. I would just need some help to make it more robust dealing with some exception if connection is interrupted or maybe the interface of internet connection changes (https://github.com/danimtb/dasshio/issues/21).

Those are minor issues that hit few users so it is not a big deal. However a little help is always good.

I think dassher addon is really good and might work out of the box, specially for those users who used dasher before to moving to hass.io

**Comment by frenck** [comment]
So what is the main difference between dasher and dasshio?

**Comment by danimtb** [comment]
Dasshio is implemented over a simple python script using scapy library, using the UI of hass.io addons for the options.

Dasher-addon is an adaptation of Dasher originally implemented in JS and the configuration is done editing a plan config.json file in the file directory (does not use hass.io UI).

However, both do exactly the same thnig.

**Comment by james-fry** [comment]
Some other points:
- Dasher has built in support for other services than just HA - see https://github.com/maddox/dasher
- Dasher's config JSON is open ended and not suitable for definition via hass.io options (I tried and failed. It would be possible if you change dasher code, but I wanted to keep the pure dasher source so I can merge in any upstream changes).
- There are people already using dasher who have not yet moved to hassio. They would be able to migrate to dasher based addon just by copying their config.json to correct dir.
- Dassio supports config via hass.io options by design, which is nice :)
- Both support ARP and UDP buttons IIRC
- Actually I am no longer using amazon dash buttons... so my ongoing support will be theoretical :) (the 5ish second lag just wasnt accepted by my family and there are super cheap alternatives such as xiaomi zigbee stuff)

- Why not run a poll on the HA forum to get input from the community re which they would prefer?

**Comment by mattlward** [comment]
You mention the Xiaomi switches... what hub are you using?  Do they react quickly, my only complaint with Dash button is the response time.  Also dasshio stops every few days...

**Comment by sveip** [comment]
Deconz should support the zigbee Xiaomi buttons.

**Comment by james-fry** [comment]
I'm using the xiaomi hub, but the recommendation for deconz is also good I believe. 
The Xiaomi hub has mature support in HA.
The xiaomi buttons (I have both versions, round and square) react instantly.

**Comment by mattlward** [comment]
Wish I could use my Hue hub... The Xiaomi buttons look nice to me as well.

**Comment by frenck** [comment]
Closing this suggestion, now the Dash buttons are discontinued
