### ISSUE TITLE
❇ Zoneminder

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#31]
# Problem/Motivation
ZoneMinder is a full-featured, open source, state-of-the-art video surveillance software system. Monitor your home, office, or wherever you want. Using off the shelf hardware with any camera, you can design a system as large or as small as you need.

## Ref

https://www.zoneminder.com/
https://home-assistant.io/components/zoneminder/

**Comment by NaffanDroo** [comment]
Zoneminder can be a pain to install manually, if it was dockerised into hass.io repository it would be great! I had it running on bare raspbian a while back but have since moved to hass.io.

Looks like a the ZM Devs have already been using docker for development: https://github.com/ZoneMinder/ZoneMinder/wiki/Docker

**Comment by iantrich** [comment]
@NaffanDroo have you tried out Shinobi?

**Comment by nickdaria** [comment]
Just adding in a little note for anyone working on this, ZoneMinder can get very resource intensive if you have a few cameras with motion detection zones. I can't say for any newer versions since I moved to Blue Iris but just a note

**Comment by frenck** [comment]
I've looked at many solutions. Right now, we provide motionEye, which is pretty decent and OK.

I'll keep it at that for now.
