### ISSUE TITLE
❇ OpenCV

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#35]
# Problem/Motivation
OpenCV is a popular computer vision library, and there is a [Home-assistant component ](https://home-assistant.io/components/image_processing.opencv/) which provides facial recognition. However installation of OpenCV is [quite involved](https://www.pyimagesearch.com/2017/09/04/raspbian-stretch-install-opencv-3-python-on-your-raspberry-pi/) and time consuming. Proposal is containerised [install of OpenCV](https://hub.docker.com/r/demosense/raspberrypi3-opencv/). It would also be nice if there were a way to add community selected classifiers that could then be used by the HA component.

# References
https://home-assistant.io/components/image_processing.opencv/
https://www.pyimagesearch.com/2017/09/04/raspbian-stretch-install-opencv-3-python-on-your-raspberry-pi/
http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_objdetect/py_face_detection/py_face_detection.html#face-detection

**Comment by robmarkcole** [comment]
This should speed things up: https://github.com/tdicola/pi_python_opencv_contrib

**Comment by mickdekkers** [comment]
@robmarkcole good find! I'm also quite interested in this.

I'm not terribly familiar with Docker or the Hassio plugin system yet, so I'm wondering if the OpenCV addon could be set up so that you could also `import cv2` in your own python scripts, just like in a regular installation.

My use case is fairly simple. I have a couple IP cameras hooked up to my Home Assistant, but the image quality isn't great. To fix that, I'd like to write a small image processing script that can plug into a camera feed to improve the contrast. I'm hoping to use something like OpenCV's [CLAHE algorithm](https://docs.opencv.org/3.1.0/d5/daf/tutorial_py_histogram_equalization.html), so detail is preserved.

Object detection also sounds exciting 😄

**Comment by robmarkcole** [comment]
Hi @mickdekkers you should checkout [camera-proxy](https://www.home-assistant.io/components/camera.proxy/), but RE opencv [my idea](https://github.com/robmarkcole/HASS-rest-image-process) is to expose as a REST service, so it is accesible by any device on the network. Thoughts?

**Comment by sveip** [comment]
Would the Rpi be powerful enough to do image processing on a video stream?

**Comment by robmarkcole** [comment]
Depends on #pixels and FPS, does Google turn up anything?
However the HA front end only updates camera feeds at 1 FPS I believe so there is no value at processing any faster..?

**Comment by sveip** [comment]
Sure, but how do you make sure Tha the frame that is displayed in HA is the
one that is processed? Or is the idea to drop fram rate-1 frames in opencv
and then forward only processed frames? Sounds feasible, but don't know how
that would work with other camera components. Maybe you need a new opencv
component as well?

**Comment by robmarkcole** [comment]
@sveip checkout [camera-proxy](https://www.home-assistant.io/components/camera.proxy/) 
I propose [adding a method](https://github.com/home-assistant/home-assistant/blob/c3974e540b3602d04eea1205701baf42e223e45b/homeassistant/components/camera/proxy.py#L59) that would post the raw image to the opencv endpoint and display the returned (processed) image.

**Comment by sveip** [comment]
Looks good.
