### ISSUE TITLE
❇ SickRage Add-on

### ISSUE THREAD

**Issue by iantrich** [hassio-addons/repository#84]
Docker setup: https://hub.docker.com/r/linuxserver/sickrage/

<blockquote></blockquote>

**Comment by frenck** [comment]
I've been split on this request. While fairly easy to create and used quite a lot (discovered after some googling and looking at download stats on different places), this add-on would be really popular. 

Nevertheless, the add-on provides users an easy access into doing things that are considered illegal in most countries. This is a piece of open source software, which by itself, isn't illegal, although providing or helping people with illegal activities can be enough for being sued as well (at least in my country). 

I'm not feeling comfortable supporting these type of applications in the Community Add-ons repository because of these reasons. So I have to decline.

**Comment by iantrich** [comment]
I think that's a smart call
